export const writerCategoryDescriptions = {
    "verbose typer": "Elaborates endlessly with long messages and high vocabulary variety.",
    "ranting typer": "Long, negative rants \u2014 often emotionally charged.",
    "neutral typer": "Short, balanced messages without strong sentiment.",
    "slammer": "Packs intense emotion, enthusiasm, and repetition \u2014 like slamming keys.",
    "energetic typer": "Excited and expressive with lots of exclamations!",
    "hasty typer": "Quick and short bursts of low-effort text.",
    "pottymouth": "Frequent profanity and negative tone.",
    "repetitive typer": "Says the same things over and over with low word diversity.",
    "formal typer": "Likes punctuation and capital letters \u2014 very proper.",
    "punctuator": "Uses punctuation more than actual words.",
    "excited typer": "Draws out words like heyyy!!! or yesssss.",
    "all-caps typer": "Loves caps \u2014 might be shouting.",
    "happy typer": "Optimistic, fast-paced, and cheerful.",
    "sleepy typer": "Slow, dull, or uninspired messages.",
    "nervous typer": "Rapid short bursts \u2014 possibly anxious.",
    "scripted typer": "Types like a bot \u2014 repetitive formatting and patterns.",
    "copy-paste typer": "Just dumps tons of copied content.",
    "chronically typing typer": "Always typing. Long messages, frequently.",
    "academic typer": "Structured, intelligent tone with long words and good formatting.",
    "emojinal typer": "Expressive and emotional \u2014 with lots of emojis \ud83d\ude0a",
    "doomer typer": "Dark, hopeless vibes in the message.",
    "sarcastic typer": "Fake positivity masking deeper negativity.",
    "troll typer": "Provocative or intentionally toxic for fun.",
    "baby typer": "Short, simple words. Feels underdeveloped.",
    "stream-of-conscious typer": "Unfiltered. Long, rambly, little punctuation.",
    "undefined typer": "Couldn\u2019t classify your style \u2014 very unique!"
  };